### ISSUE TITLE
自动参数搜索相关问题

### ISSUE THREAD

**Issue by BIGWangYuDong** [misads/cv_template#1]
hello，
想咨询一下 自动参数搜索怎么应用，相关代码在那儿体现的~

谢谢！

**Comment by misads** [comment]
这是一个之前在测试中的功能，就是配置一个yml文件给定所有参数的选择范围，然后一键全部运行，由于实用性不强当前版本已经删除了。
历史版本的代码可以参考：
https://github.com/misads/cv_template/blob/479956b796aef6739af0a2581ebf867cf37b647c/runx.py
https://github.com/misads/cv_template/blob/479956b796aef6739af0a2581ebf867cf37b647c/sweep.yml
